application/src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity()
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $resetToken;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }
}

application/templates/base-includes/flashmessages.html.twig
<div class="row p-2">
  <div class="col">
  {% for label, messages in app.flashes %}
    {% for message in messages %}
      <div class="alert alert-{{label}} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
      </div>
    {% endfor %}
  {% endfor %}
  </div>
</div>

application/templates/base-includes/footer.html.twig
<div class="col-12" >
  <div class="alert alert-info" id="footer" >
    <div class="row">
      <div class="col links">
        <a href="{{path("legal_notices")}}">Mentions légales</a> -
        <a target="_blank" href="https://gricad-gitlab.univ-grenoble-alpes.fr/elan/elan-vitrine">Code source</a> -
        {% if not is_granted('IS_AUTHENTICATED_REMEMBERED') %}
            <a href="{{ path('app_register') }}">S'enregistrer</a> -
            <a href="{{ path('app_login') }}">Se connecter</a> -
        {% else %}
            <a href="{{ path('app_logout') }}">Se déconnecter</a>
        {% endif %}
         (Crédits photo : Bertrand93 - 2011 - CC-BY-SA-3.0)
      </div>
    </div>
  </div>
</div>

application/templates/base-includes/header.html.twig
<nav class="navbar navbar-expand navbar-light bg-light">
  <div class=" w-100 order-1 order-md-0">
    <div class="navbar-nav mr-auto">
      <a class="navbar-brand" href="{{ path('homepage') }}">
        <i class="fas fa-shoe-prints"></i> TEMPLATE
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% if isAdmin %}
        <a class="nav-item nav-link" href="{{ path('admin_list_users') }}">
          <i class="fas fa-users"></i> Utilisateurs
        </a>
      {% endif %}
    </div>
  </div>
  <div class="navbar-collapse collapse w-100 order-2">
    <ul class="navbar-nav ml-auto">
      {% if not is_granted('IS_AUTHENTICATED_REMEMBERED') %}
        <li class="nav-item">
          <a class="nav-item nav-link" href="{{ path('app_register') }}">S'enregistrer</a>
        </li>
        <li class="nav-item">
          <a class="nav-item nav-link" href="{{ path('app_login') }}">Se connecter</a>
        </li>
      {% else %}
        <li class="navbar-text">
          <i class="fas fa-user"></i>
          {{ app.user.username }}
          {{isAdmin ? "(admin)" : "(user)" }}
        </li>
        <li class="nav-item">
          <a class="nav-item nav-link" href="{{ path('app_logout') }}">
            <i class="fas fa-sign-out-alt"></i>
            Se déconnecter
          </a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>